#!/bin/sh

# Define the function to set the git hooks path
set_git_hooks_path() {
  git config core.hooksPath "$1"
}

# Check the argument and call the function with the appropriate path
case "$1" in
  "ios")
    echo "🍎 iOS 세팅으로 설정합니다."
    set_git_hooks_path "./iOS/.githooks/"
    ;;
  "be")
    echo "💽 BE 세팅으로 설정합니다."
    set_git_hooks_path "./BE/.githooks/"
    ;;
  *)
    echo "Invalid argument. Use 'ios' for iOS setup or 'be' for Backend setup."
    exit 1
    ;;
esac