#!/bin/sh

matrix="{\"include\":["
first_entry=true
for scheme in $(xcodebuild -workspace iOS/MusicSpot.xcworkspace -list | grep -A 100 "Schemes:" | grep -v "Schemes:" | sed '/^$/d' | sed 's/^[ \t]*//'); do
    if [[ $scheme == *"Tests" ]]; then
      if [ "$first_entry" = true ]; then
        first_entry=false
      else
        matrix+=","
      fi
    matrix+="{\"scheme\":\"$scheme\"}"
    fi
done
matrix+="]}"
echo $matrix