#!/bin/sh

LINTPATH='.swiftlint.yml'
declare -a PATHS=("MSCoreKit" "MSFoundation" "MSUIKit" "MusicSpot")
failures=""

for path in "${PATHS[@]}"; do
    if [ -d "$path" ]; then
        echo "👀 Running SwiftLint for $path"
        result=$(swiftlint lint --progress --config $LINTPATH $path)
        if [ "$result" == '' ]; then
            echo "✅ Lint succeed for $path\n"
        else
            echo "❌ Lint failed for $path\n"
            failures+="\n\033[1m✔️ $path\033[0m\n$result\n"
        fi
    else
        echo "❓ $path directory does not exist."
        exit 1
    fi
done

if [ ! -z "$failures" ]; then
    echo "$failures"
    exit 1
else
    echo "✨ All linting checks passed. Ready to commit."
    gitmoji -c
fi
